/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { UrbanDataPoint, IterationLoop } from './types';

export const SAMPLE_DATA: UrbanDataPoint[] = [
  {
    id: 'DP.C1.0.0',
    distance: 0,
    featureValue: 'origin--anchor',
    source: 'Mapillary',
    taxonomy: 'MARKER_OBJECT',
    situation: 'SPATIAL_MATRIX',
    situationDesc: 'Initial alignment node. Establishes the orientation of the 15m path vector.',
    impulse: 'INJECTION',
    bodyAction: 'Settle at Node A. Establish two-point contact.',
    spatialOutput: 'stable platform, ground baseline',
    bodyLocus: 'feet, spine',
    movementInstruction: 'Both feet fully grounded. The linear tension rope is touched lightly but not yet pulled. Maintain orientation.',
  },
  {
    id: 'DP.C1.1.1',
    distance: 1.87,
    featureValue: 'object--traffic-cone',
    source: 'Mapillary',
    taxonomy: 'SOLID_MASS_OBJECT',
    situation: 'MASS',
    situationDesc: 'A solid mass object protrudes into the walking volume, demanding spatial compression.',
    impulse: 'COMPRESSION',
    bodyAction: 'Narrow at the shoulders, clavicle, and elbows.',
    spatialOutput: 'compressed body dynamic, narrow corridor',
    bodyLocus: 'shoulder, clavicle, elbow',
    movementInstruction: 'Pull shoulders inward. Narrow your body\'s silhouette. Minimize transverse volume as you pass the barrier.',
  },
  {
    id: 'DP.C1.2.1',
    distance: 3.55,
    featureValue: 'construction--flat--driveway',
    source: 'Mapillary',
    taxonomy: 'TEXTURE_OBJECT',
    situation: 'ELEVATION',
    situationDesc: 'The horizontal walking plane is disrupted by an asymmetric slope or change in material.',
    impulse: 'ASYMMETRIC',
    bodyAction: 'Asymmetric weight shift. Left foot anchors while right foot drags slightly.',
    spatialOutput: 'asymmetric track, uneven step',
    bodyLocus: 'hip, ankle, left foot',
    movementInstruction: 'Anchor one foot fully while letting the other step with a subtle lateral tilt. Absorb the incline through the knee.',
  },
  {
    id: 'DP.C1.1.2',
    distance: 4.27,
    featureValue: 'object--traffic-cone',
    source: 'Mapillary',
    taxonomy: 'SOLID_MASS_OBJECT',
    situation: 'MASS',
    situationDesc: 'A solid mass object continues to restrict the pathway, requiring continued core compression.',
    impulse: 'COMPRESSION',
    bodyAction: 'Sustained narrowing of core and limb profile.',
    spatialOutput: 'compressed body, restricted path width',
    bodyLocus: 'shoulders, torso',
    movementInstruction: 'Keep elbows locked close to the ribs. Retain your compressed stance.',
  },
  {
    id: 'DP.C1.1.3',
    distance: 4.51,
    featureValue: 'object--traffic-cone',
    source: 'Mapillary',
    taxonomy: 'SOLID_MASS_OBJECT',
    situation: 'MASS',
    situationDesc: 'A final low obstacle blocks the path\'s edge, creating lateral force.',
    impulse: 'COMPRESSION',
    bodyAction: 'Elbows press tightly against the chest.',
    spatialOutput: 'locked axis, tight passage',
    bodyLocus: 'arms, ribcage',
    movementInstruction: 'Execute maximum narrowing. Keep the path vector tightly aligned.',
  },
  {
    id: 'DP.C1.2.2',
    distance: 7.16,
    featureValue: 'object--support--utility-pole',
    source: 'Mapillary',
    taxonomy: 'SOLID_MASS_OBJECT',
    situation: 'MASS',
    situationDesc: 'A vertical utility pole restricts overhead and side clearance, creating asymmetric mass.',
    impulse: 'COMPRESSION',
    bodyAction: 'Sustained narrowed body. Head tilts slightly downward.',
    spatialOutput: 'sustained narrowed body, vertical axis pressure',
    bodyLocus: 'head, shoulders',
    movementInstruction: 'Narrow the shoulder width. Tilt the crown of the head slightly away from the pole to avoid vertical impact.',
  },
  {
    id: 'DP.C1.3.1',
    distance: 12.15,
    featureValue: 'regulatory--no-right-turn--g1',
    source: 'Mapillary',
    taxonomy: 'REGULATORY_OBJECT',
    situation: 'AUTHORITY',
    situationDesc: 'The regulatory object declares a directional prohibition at the edge of the path, demanding sudden suspension.',
    impulse: 'FREEZE',
    bodyAction: 'Sudden arrest of momentum at the pelvis and spine.',
    spatialOutput: 'locked axis, rigid posture, internal torque',
    bodyLocus: 'spine, pelvis, hip',
    movementInstruction: 'Stop all forward drive immediately. Keep the hand gripping the line. Let the hip tremor once. Hold the locked axis.',
  },
  {
    id: 'DP.C1.4.1',
    distance: 12.45,
    featureValue: 'object--sign--advertisement',
    source: 'Mapillary',
    taxonomy: 'SEMANTIC_OBJECT',
    situation: 'SEMANTIC',
    situationDesc: 'Commercial visual noise demands ocular fixation, diverging attention from the physical vector.',
    impulse: 'FIXATION',
    bodyAction: 'The head and eyes lock toward the display, while the limbs maintain forward tension.',
    spatialOutput: 'split focus, axial drift',
    bodyLocus: 'neck, eyes, head',
    movementInstruction: 'Extend a visual gaze line toward the sign. Keep hands engaged on the path tension rope. Carry your body forward but look sideways.',
  },
  {
    id: 'DP.C1.5.1',
    distance: 14.31,
    featureValue: 'object--manhole',
    source: 'Mapillary',
    taxonomy: 'GROUND_TEXTURE_OBJECT',
    situation: 'ELEVATION',
    situationDesc: 'An unstable surface panel directly underneath the foot creates slip-potential.',
    impulse: 'GLITCH',
    bodyAction: 'High-frequency jitter of the lower limb. Tremor in place.',
    spatialOutput: 'slip-potential, unstable baseline',
    bodyLocus: 'ankle, foot, knees',
    movementInstruction: 'Initiate a high-frequency jitter in your stepping foot. Tremble in place. Maintain visual hold of the next node.',
  },
  {
    id: 'DP.C1.0.1',
    distance: 15,
    featureValue: 'terminal--contact',
    source: 'Mapillary',
    taxonomy: 'MARKER_OBJECT',
    situation: 'SPATIAL_MATRIX',
    situationDesc: 'Terminal boundary contact. The score system completes.',
    impulse: 'CONSTANT',
    bodyAction: 'Release tension rope. Complete deceleration.',
    spatialOutput: 'neutral baseline, released tension',
    bodyLocus: 'arms, legs',
    movementInstruction: 'Release your grip on the tension rope. Return to a neutral upright posture. Step firmly into Node B.',
  },
];

export const ITERATION_LOOPS: IterationLoop[] = [
  {
    id: 'loop-1',
    name: 'Compression Loop',
    description: 'Repeatedly pulses the body narrowness at close range obstacles. Tests sustained transverse reduction.',
    impulses: ['COMPRESSION', 'ACCELERATION', 'COMPRESSION'],
    variableCount: 3,
    lockingRule: 'Lock torso axis; reduce shoulder tracking width by 40% per cycle.',
    outputResidue: 'Sustained rigid torso tension, residual clavicle compression.'
  },
  {
    id: 'loop-2',
    name: 'Fixation Loop',
    description: 'Alternates gaze lines between semantic signage and the physical pathway axis. Tests neck/torso split tension.',
    impulses: ['FIXATION', 'CONSTANT', 'FIXATION', 'CONSTANT'],
    variableCount: 4,
    lockingRule: 'Lock neck rotation to 30 degrees; delay torso adjustment by 1.2s.',
    outputResidue: 'Cervical rotation fatigue, slight lateral deviation of foot tracking.'
  },
  {
    id: 'loop-3',
    name: 'Glitch Loop',
    description: 'Triggers high-frequency ankle trembling and stability loss over ground disruptions.',
    impulses: ['GLITCH', 'ASYMMETRIC', 'GLITCH'],
    variableCount: 3,
    lockingRule: 'Tremor frequency 8Hz; anchor opposite foot fully.',
    outputResidue: 'Instability spikes, high muscular micro-tension residue.'
  },
  {
    id: 'loop-4',
    name: 'Acceleration Loop',
    description: 'Increases walking speed and lean angle along clear linear stretches.',
    impulses: ['ACCELERATION', 'CONSTANT', 'ACCELERATION'],
    variableCount: 3,
    lockingRule: 'Increase step frequency by 15% per meter; increase torso lean angle by 5 degrees.',
    outputResidue: 'Sustained forward momentum, high rope-tension index.'
  }
];
